# Site settings
title: This is where I talk
email: sandeep@listenloop.com
description: > # this means to ignore newlines until "baseurl:"
  Here i plan to share things I get to do as CTO @ listenloop,
  general technology things which interest me and every now and then perhaps I'll talk about other stuff which affects me.
# baseurl: "sandeep45.github.io" # the subpath of your site, e.g. /blog/
url: "http://sandeep45.github.io" # the base hostname & protocol for your site
twitter_username: sandeeparneja
github_username:  sandeep45
# Build settings
markdown: kramdown
highlighter: rouge
permalink: date
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
plugins:
- jekyll-feed
theme: jekyll-theme-cayman